### ISSUE TITLE
Problem during 'dev run build'

### ISSUE THREAD

**Issue by brendan-holmes** [saberland/create-portfolio#164]
Using the quick start guide, had this error when running `npm run build`:

```
[error] RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at C:\Projects\create-portfolio\test-site\node_modules\feed\lib\atom1.js:57:32
    at Array.map (<anonymous>)
    at Object.default (C:\Projects\create-portfolio\test-site\node_modules\feed\lib\atom1.js:52:15)
    at Feed.atom1 (C:\Projects\create-portfolio\test-site\node_modules\feed\lib\feed.js:17:58)
    at generateFeed (C:\Projects\create-portfolio\test-site\node_modules\saber-plugin-feed\lib\index.js:124:67)
    at async Promise.all (index 0)
    at async C:\Projects\create-portfolio\test-site\node_modules\saber-plugin-feed\lib\index.js:43:5
```

No issues with `npm run dev`.

```
$ npm -v
6.13.1
$ node -v
v13.2.0
```

Full output:
```
$ npm run build

> my-site@ build C:\Projects\create-portfolio\my-site
> saber build

[info] Using config file: saber-config.js
[info] Using theme: portfolio
[info] Fetching GitHub data for brendan-holmes..
[info] Using 2 plugins from config file
[success] Compiled server successfully in 5.5s!
[success] Compiled client successfully in 8.4s!
[info] Generating posts\my-first-post\index.html
[info] Generating about\index.html
[info] Generating index.html
[info] Generating posts\index.html
[info] Generating tags\life\index.html
[info] Generating 404.html
[error] RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at C:\Projects\create-portfolio\my-site\node_modules\feed\lib\atom1.js:57:32
    at Array.map (<anonymous>)
    at Object.default (C:\Projects\create-portfolio\my-site\node_modules\feed\lib\atom1.js:52
    at Feed.atom1 (C:\Projects\create-portfolio\my-site\node_modules\feed\lib\feed.js:17:58)
    at generateFeed (C:\Projects\create-portfolio\my-site\node_modules\saber-plugin-feed\lib\
    at async Promise.all (index 0)
    at async C:\Projects\create-portfolio\my-site\node_modules\saber-plugin-feed\lib\index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-site@ build: `saber build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-site@ build script.
```

**Comment by bruhtus** [comment]
I have the same problem, the only difference is that i'm on linux. Is there some kind of problem with newer npm version?

**Comment by rjworks** [comment]
Any update @egoist?

**Comment by rjworks** [comment]
Any updates @egoist ?
