### ISSUE TITLE
Error: siteConfig.url is required for saber-plugin-feed

### ISSUE THREAD

**Issue by steveny9911** [saberland/create-portfolio#63]
Hi there,
I'm following the **Quick start** guide and I ran into some problem when building the site with `yarn saber` ; I have the full error message down below. 
My apology that I have little understanding about node/npm/yarn; it would be great if any guidance can be provided, or feel free to direct me to other places that are more appropriate. Thanks.

```
node -v: v12.7.0
npm -v: 6.10.0
```

```
error Error: siteConfig.url is required for saber-plugin-feed
    at Object.exports.apply (C:\Users\styang\Desktop\my-site\node_modules\saber-plugin-feed\lib\index.js:22:11)
    at Saber.applyPlugin (C:\Users\styang\Desktop\my-site\node_modules\saber\lib\index.js:204:12)
    at Saber.prepare (C:\Users\styang\Desktop\my-site\node_modules\saber\lib\index.js:171:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Saber.serve (C:\Users\styang\Desktop\my-site\node_modules\saber\lib\index.js:342:5)
```

---
Full message
```
C:\Users\styang\Desktop\my-site>npm run dev

> my-site@ dev C:\Users\styang\Desktop\my-site
> saber

info Using config file: saber-config.js
info Using theme: portfolio
info Fetching GitHub data for steveny9911..
info Using 2 plugins from config file
error Error: siteConfig.url is required for saber-plugin-feed
    at Object.exports.apply (C:\Users\styang\Desktop\my-site\node_modules\saber-plugin-feed\lib\index.js:22:11)
    at Saber.applyPlugin (C:\Users\styang\Desktop\my-site\node_modules\saber\lib\index.js:204:12)
    at Saber.prepare (C:\Users\styang\Desktop\my-site\node_modules\saber\lib\index.js:171:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Saber.serve (C:\Users\styang\Desktop\my-site\node_modules\saber\lib\index.js:342:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-site@ dev: `saber`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-site@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\styang\AppData\Roaming\npm-cache\_logs\2019-07-24T17_52_10_343Z-debug.log
```

**Comment by steveny9911** [comment]
I realized there was a demo project; my `saber-config.js` was missing

```js
module.exports = {
  siteConfig: {
    description: 'Description',
    url: 'URL'
  }
}
```

**Comment by egoist** [comment]
Thanks for reporting, I also fixed it in `create-portfolio` (https://github.com/saberland/create-portfolio/commit/3d98910)
